Saved selected location to user's currentLatLngStr and changed UI
ubclaunchpad/driver pull request #118
Opened 2017-06-29 23:15 UTC by stevenshih1997

Basically duplicated the code for destinationAutocompleteFragment.setOnPlaceSelectedListener for currentAutocompleteFragment to save user's selected location to currentLatLngStr field. Also edited the UI to allow a consistent design in the activity.

2017-07-08 19:31 UTC, jsondoo requested changes

2017-07-08 19:31 UTC, jsondoo commented on app/src/main/java/com/android/ubclaunchpad/driver/UI/DestinationActivity.java
> +                            .child(StringUtils.FirebaseDestinationLatLngEndpoint)
So if you use StringUtils.FirebaseDstinationLatLngEndpoint that is updating the destinationLatLngStr in Firebase so u should change this to update currentLatLngStr

2017-07-10 02:41 UTC, stevenshih1997 commented on app/src/main/java/com/android/ubclaunchpad/driver/UI/DestinationActivity.java
> +                            .child(StringUtils.FirebaseDestinationLatLngEndpoint)
Whoops. I've fixed the typo and committed the changes. Thanks!

2017-07-13 01:57 UTC, jsondoo approved these changes

2017-07-14 01:02 UTC, merged