Driv 72
ubclaunchpad/driver pull request #127
Opened 2017-08-04 10:10 UTC by grig-guz

2017-08-05 20:26 UTC, frostyshadows requested changes

2017-08-05 20:26 UTC, frostyshadows commented on app/src/main/java/com/android/ubclaunchpad/driver/session/DriverPassengersActivity.java
> +        String sessionName = (String) getIntent().getBundleExtra("firebaseData").get(StringUtils.FirebaseSessionName);
use string constants for "firebaseData" and "driverUid", so that we won't make a typo when typing the endpoint name

2017-08-05 20:26 UTC, frostyshadows commented on app/src/main/java/com/android/ubclaunchpad/driver/session/DriverPassengersActivity.java
> +        startButton = (Button) findViewById(R.id.start_button);
you can use ButterKnife instead of findViewByIds

2017-08-05 20:26 UTC, frostyshadows commented on app/src/main/java/com/android/ubclaunchpad/driver/session/SessionInfoActivity.java
> +                intent.putExtra("firebaseData", data);
use string constant

2017-08-05 20:26 UTC, frostyshadows commented on app/src/main/java/com/android/ubclaunchpad/driver/session/SessionInfoActivity.java
> +                                data.putString("driverUid", UID);
string constant

2017-08-05 20:26 UTC, frostyshadows commented on app/src/main/java/com/android/ubclaunchpad/driver/session/DriverPassengersActivity.java
> +        session.child(StringUtils.FirebaseSessionDriverPassengers).child(driverUid).addChildEventListener(listener);
why is this listening for changes for driverUid? I thought you'd want to listen for changes to either the drivers or passengers endpoint in the session to see if a new user's added to the session, but might be understanding it wrong.

2017-08-05 20:26 UTC, frostyshadows commented on app/src/main/java/com/android/ubclaunchpad/driver/session/DriverPassengersActivity.java
> +        driverName = (TextView) findViewById(R.id.driver_name);
you can use ButterKnife for this, for example @BindView instead of findViewById()

2017-08-05 20:26 UTC, frostyshadows commented on app/src/main/java/com/android/ubclaunchpad/driver/session/DriverPassengersActivity.java
> +        String sessionName = (String) getIntent().getBundleExtra("firebaseData").get(StringUtils.FirebaseSessionName);
use string constants for "firebaseData" and "driverUid", so that we won't make a typo when typing the endpoint name

2017-08-05 20:26 UTC, frostyshadows commented on app/src/main/java/com/android/ubclaunchpad/driver/session/SessionInfoActivity.java
> +                                data.putString("driverUid", UID);
string constant

2017-08-05 20:26 UTC, frostyshadows commented on app/src/main/java/com/android/ubclaunchpad/driver/session/SessionInfoActivity.java
> +                                            data.putString("driverUid", UID);
string constant

2017-08-05 20:26 UTC, frostyshadows commented on app/src/main/java/com/android/ubclaunchpad/driver/session/SessionInfoActivity.java
> +                intent.putExtra("firebaseData", data);
use String constant

2017-08-05 20:26 UTC, frostyshadows commented on app/src/main/java/com/android/ubclaunchpad/driver/session/SessionInfoActivity.java
> +    private void initializeListeners(final ArrayAdapter<String> adapter, final String sessionName) {
this is a really big Activity since you're making 3 listeners...maybe you could move some of the code into a new non-Activity class?

2017-08-05 20:26 UTC, frostyshadows commented on app/src/main/java/com/android/ubclaunchpad/driver/session/SessionInfoActivity.java
> +    private Runnable startActivityTask(final Bundle data) {
can you call this something like startDriverPassengersActivityTask instead since it always starts that specific activity?

2017-08-05 21:22 UTC, frostyshadows commented on app/src/main/java/com/android/ubclaunchpad/driver/session/DriverPassengersActivity.java
> +                String uid = dataSnapshot.child(StringUtils.FirebaseSessionDriverPassengers).getValue(String.class);
I get NPEs here saying that it's a HashMap not a String here

2017-08-05 21:32 UTC, frostyshadows commented on app/src/main/java/com/android/ubclaunchpad/driver/session/SessionInfoActivity.java
> +                                runOnUiThread(startActivityTask(data));
it looks like this isn't tied to the Go button

2017-08-09 11:24 UTC, grig-guz commented on app/src/main/java/com/android/ubclaunchpad/driver/session/DriverPassengersActivity.java
> +        startButton = (Button) findViewById(R.id.start_button);
it looks lame but... ok

2017-08-09 11:33 UTC, grig-guz commented on app/src/main/java/com/android/ubclaunchpad/driver/session/DriverPassengersActivity.java
> +        session.child(StringUtils.FirebaseSessionDriverPassengers).child(driverUid).addChildEventListener(listener);
this thing acts when passengers and drivers are already assigned. So basically, it just works on a list of passengers for a specific driver and updates it in the activity accordingly when it gets changed by something outside. As for passengers and drivers endpoints, Session activities are responsible for them.

2017-08-09 11:33 UTC, grig-guz commented on app/src/main/java/com/android/ubclaunchpad/driver/session/SessionInfoActivity.java
> +    private void initializeListeners(final ArrayAdapter<String> adapter, final String sessionName) {
I see, I'll think about how to do that

2017-08-10 09:24 UTC, grig-guz commented on app/src/main/java/com/android/ubclaunchpad/driver/session/DriverPassengersActivity.java
> +        driverName = (TextView) findViewById(R.id.driver_name);
yeah, sure

2017-08-10 10:05 UTC, grig-guz commented on app/src/main/java/com/android/ubclaunchpad/driver/session/SessionInfoActivity.java
> +                                runOnUiThread(startActivityTask(data));
Nope, it only runs when driverPassengers map appears on the session object in firebase, which happens only after you hit Go button.

2017-08-12 21:07 UTC, chan-kelv approved these changes

2017-08-12 21:07 UTC, chan-kelv commented on app/src/main/java/com/android/ubclaunchpad/driver/session/DriverPassengersActivity.java
> +        driversPassengers = (RecyclerView) findViewById(R.id.passengers_container);
this line not needed. Butterknife takes care of this

2017-08-12 21:07 UTC, chan-kelv commented on app/src/main/java/com/android/ubclaunchpad/driver/session/SessionInfoActivity.java
> +        session.removeEventListener(passengersListener);
forgot to remove driverPassengersListener?

2017-08-14 07:40 UTC, grig-guz commented on app/src/main/java/com/android/ubclaunchpad/driver/session/SessionInfoActivity.java
> +        session.removeEventListener(passengersListener);
good catch

2017-08-14 21:18 UTC, sherry-yuan-hs approved these changes

2017-08-14 21:20 UTC, frostyshadows approved these changes

2017-08-15 07:14 UTC, merged