Lz-73 move sign out button to the action bar
ubclaunchpad/driver pull request #85
Opened 2017-05-06 21:05 UTC by Luxi-Zhao

2017-05-06 22:34 UTC, yonniluu requested changes
looks good, see if you can add a dialog to confirm that the user wants to log out so that they don't do it accidentally

2017-05-06 22:34 UTC, yonniluu commented on app/src/main/java/com/android/ubclaunchpad/driver/UI/MainActivity.java
> +
remove extra space

2017-05-06 22:34 UTC, yonniluu commented on app/src/main/java/com/android/ubclaunchpad/driver/UI/MainActivity.java
> +   // @BindView(R.id.sign_out_button) Button mSignOutButton;
you can delete it instead of commenting it out

2017-05-06 22:34 UTC, yonniluu commented on app/src/main/java/com/android/ubclaunchpad/driver/session/SessionActivity.java
> +
remove extra space

2017-05-06 22:34 UTC, yonniluu commented on app/src/main/res/layout/activity_destination.xml
> +
remove extra space

2017-05-06 22:34 UTC, yonniluu commented on app/src/main/res/layout/activity_main.xml
> + <!--   <Button
you can delete this instead of commenting it out

2017-05-06 22:34 UTC, yonniluu commented on app/src/main/res/layout/activity_session.xml
> +
remove extra space

2017-05-13 20:21 UTC, beriwanravandi commented
Confirmation dialog looks good!

2017-05-13 21:44 UTC, jsondoo commented
ActionBar change looks nice. Sign out works on my device

2017-05-13 22:25 UTC, merged